pragma solidity >=0.4.16 <0.7.0;
pragma experimental ABIEncoderV2;

enum Works {
    NONE,
    ARTICLE,
    BOOK,
    BLOG,
    CLIP,
    DIGITALDOCUMENT,
    DRAWING,
    MOVIE,
    MUSICCOMPOSITION,
    MUSICRECORDING,
    PAINTING,
    PHOTOGRAPH,
    POSTER
    SHORTSTORY,
    SOFTWAREAPPLICATION,
    SOFTWARESOURCECODE,
    THESIS,
    VISUALARTWORK,
    WEBCONTENT,
    WEBPAGE,
    WEBSITE,
    MAX
}

enum License {
    NONE,
    APACHELICENSESLICENSE20,
    GNUGENERALPUBLICLICENSEV30,
    MITLICENSE,
    BSD2CLAUSESIMPLIFIEDLICENSE,
    BSD3CLAUSENEWORREVISEDLICENSE,
    BOOSTSOFTWARELICENSE10,
    CREATIVECOMMONSZEROV10UNIVERSAL,
    ECLIPSEPUBLICLICENSE20,
    GNUAFFEROGENERALPUBLICLICENSEV30,
    GNUGENERALPUBLICLICENSEV20,
    GNULESSERGENERALPUBLICLICENSEV21,
    MOZILLAPUBLICLICENSE20,
    THEUNLICENSE,
    MAX
}
