openapi: "3.0.0"

info:
  title: "REST API for Zeus"
  description: "Server configuration for the Zeus REST API"
  version: "0.1.0"
  contact:
    email: "steve@glowkeeper.uk"

servers:
    url: "localhost"
    description: "live development server"
    variables:
        port:
            default: ":10000"

paths:
    /:
        get:
            summary:  "/"
            description: "Zeus homepage"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /help:
        get:
            summary: "/help"
            description: "Zeus REST API help"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /spons:
        get:
            summary: "/spons"
            description: "Zeus REST API spons references"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /spons-all:
        get:
            summary: "/spons-all"
            description: "Zeus REST API spons information"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /spons-total:
        get:
            summary: "/spons-total"
            description: "Zeus REST API spons total"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /spons/{sponsRef}:
        get:
            summary: "/spons/{sponsRef}"
            description: "Zeus REST API spons information"
            parameters:
                name: "sponsRef"
                in: "path"
                required: true
                description: "The spons reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /jobs:
        get:
            summary: "/jobs"
            description: "Zeus REST API jobs references"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /jobs-all:
        get:
            summary: "/jobs-all"
            description: "Zeus REST API jobs information"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /jobs-total:
        get:
            summary: "/jobs-total"
            description: "Zeus REST API jobs total"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /jobs-address/{address}:
        get:
            summary: "/jobs-address/{address}"
            description: "Zeus REST API jobs for an address"
            parameters:
                name: "address"
                in: "path"
                required: true
                description: "Jobs for a given address"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /jobs-address-status/{address}/{status}:
        get:
            summary: "/jobs-address-status/{address}/{status}"
            description: "Zeus REST API jobs for an address and with a given status"
            parameters:
                name: "address"
                in: "path"
                required: true
                description: "Jobs for a given address"
                schema:
                    type : "string"
                    minimum: 1
            otherParameters:
                name: "status"
                in: "path"
                required: true
                description: "Jobs for a given status"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /jobs-status/{status}:
        get:
            summary: "/jobs-status/{status}"
            description: "Zeus REST API jobs with a given status"
            parameters:
                name: "status"
                in: "path"
                required: true
                description: "Jobs with a given status"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /job/{jobRef}:
        get:
            summary: "/job/{jobRef}"
            description: "Zeus REST API job information"
            parameters:
                name: "jobRef"
                in: "path"
                required: true
                description: "The job reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /subbies:
        get:
            summary: "/subbies"
            description: "Zeus REST API subbies addresses"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /subbies-all:
        get:
            summary: "/subbies-all"
            description: "Zeus REST API subbies information"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /subbies-total:
        get:
            summary: "/subbies-total"
            description: "Zeus REST API subbies total"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /subbie/{subbieAddress}:
        get:
            summary: "/subbie/{subbieAddress}"
            description: "Zeus REST API subbie information"
            parameters:
                name: "subbieAddress"
                in: "path"
                required: true
                description: "The subbie reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
