openapi: "3.0.0"

info:
  title: "REST API for Provenator"
  description: "Server configuration for the Provenator REST API"
  version: "0.1.0"
  contact:
    email: "steve@glowkeeper.uk"

servers:
    url: "localhost"
    description: "live development server"
    variables:
        port:
            default: ":10000"

paths:
    /:
        get:
            summary:  "/"
            description: "Provenator homepage"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /entities:
        get:
            summary: "/entities"
            description: "Provenator REST API entity references"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /entities-all:
        get:
            summary: "/entities-all"
            description: "Provenator REST API entities information"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /entities-total:
        get:
            summary: "/entities-total"
            description: "Provenator REST API entities total"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /entities/{entitiesRef}:
        get:
            summary: "/entities/{entitiesRef}"
            description: "Provenator REST API entities information"
            parameters:
                name: "entitiesRef"
                in: "path"
                required: true
                description: "The entities reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /entities-types/{entitiesRef}:
        get:
            summary: "/entities-types/{entitiesRef}"
            description: "Provenator REST API entity type information"
            parameters:
                name: "entitiesRef"
                in: "path"
                required: true
                description: "The entities reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
    /artefacts:
        get:
            summary: "/artefacts"
            description: "Provenator REST API artefacts references"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /artefacts-all:
        get:
            summary: "/artefacts-all"
            description: "Provenator REST API artefacts information"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /artefacts-total:
        get:
            summary: "/artefacts-total"
            description: "Provenator REST API artefacts total"
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "array"
                        items:
                          type: "string"
    /artefacts/{artefactsRef}:
        get:
            summary: "/artefacts/{artefactsRef}"
            description: "Provenator REST API specific artefacts"
            parameters:
                name: "artefactsRef"
                in: "path"
                required: true
                description: "artefacts for a given reference"
                schema:
                    type : "string"
                    minimum: 1
            responses:
                '200':
                  description: "Success"
                  content:
                    application/json:
                      schema:
                        type: "string"
                        items:
                          type: "string"
